version: "3.4"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data:/var/lib/mysql

  adminer_mysql:
    image: adminer:latest
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    env_file:
      - ./.env
    ports:
      - 8888:8080

  redis:
    image: 'redis:5-alpine'
    ports:
      - 6379:6379

  node_app:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/db-ec
    ports:
      - 4000:4000
    command: >
      sh -c "npx prisma migrate dev && 
      npm run dev"

volumes:
  mysql_db_data:





